{% set version = "1.0.9" %}
{% set commit = "cb3b00fd5e23eb6763012582d2bc8858809267d7" %}

package:
    name: pyspharm
    version: {{ version }}

source:
    fn: {{ commit }}.tar.gz
    url: https://github.com/jswhit/pyspharm/archive/{{ commit }}.tar.gz
    md5: 6d942bdadd4cb26dfe9c3ee01fa149d1

build:
    number: 1
    skip: True  # [win and py3k or win64]

requirements:
    build:
        - python
        - numpy x.x
        - mingwpy  # [win]
        - gcc  # [not win]
    run:
        - python
        - numpy x.x
        - libgcc  # [linux]
        - libgfortran  # [osx]

test:
    imports:
        - spharm
    commands:
        - conda inspect linkages -n _test pyspharm  # [not win]

about:
    home: https://code.google.com/p/pyspharm/
    license: MIT and https://www2.cisl.ucar.edu/resources/legacy/spherepack/license
    summary: 'Provides an object-oriented python interface to the NCAR SPHEREPACK library.'

extra:
    recipe-maintainers:
        - ajdawson
        - ocefpaf
