travis:
  secure:
    BINSTAR_TOKEN: ZUVzwHAXVd5rkACUTCYdWS1b4cm4qh892/ZzS7IQJU7ufh1FFD4pzaaxUzNsbdSQUZnyD28935cD6g8NnqiMPGMDN+2i/L8sj/VDyrla8ZSYgyDnW7DEsaY6TOAWYbXbqPWHNSYB8Kk9e1RMYdhjE5lIgj3q+/ak+omFCEAqRd1QuZWlP2fQ/pBuvLtFxlBt4PIR8Wjf4oSkLsAQMBQ0locOAeBudYYBnmbeAqWMN1q2m97lg9Qthor0SKcYVumacXHVD99nT1zWtFgKjOqxw03KN6RUgsoxnu0MwkNydbSsiZMQdI2x5AC6CsxvrRY/+efJbiQHLYuBlRZk/9JalVAfqIFSvPX63yW047lK9xjoMZzmQL+QqZS8twRQDz8i1ruAQHwiineHT63iZ/7nTdpDThQVJIRqXF7+z7MVP9W5o5YO8KgysHvVEZnoWBwr/SnPQ829bbHJrmx3Cv5MDr4gLj6CMFwhozE8+b3KVwkK4LIddaGAy5bm3yRIhQm30tAnXNMoFyR5p0iAphUxuQlUAsgJuSM6k4EemCLEDCww7AYUxM50i6k/4ez7LmpkTvvApdrsC45xn1YisGuUUMm1zlhl851C7sVhtje4K+bd0E2XXQ4AgatWYyfcYapRtc/VVJGyUw87DZa68N7kkbG8J+PHE+HH/8XcHf1W5lU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
