travis:
  secure:
    BINSTAR_TOKEN: ohQOFxnleZhCkty/69oXTF/rVhBqCwihWoOE2pSEzlH3VEuAKzbizNNArcnjLKH0DYc7+ERxm5pDXjIbsERq5fOJ/qQfuhKnJca859DnGlp8Vb3VzNE1/8hLxre7fm/lQxMGQiwhVx6bkrWArhD5WAiztK7tanY/YVkXPveAKPuWNVlaNwd9Mt0op9+DZRnnIMmTzbJOpAdixkgZzaJH6qaPgbzSYxbUJwMXAKyI6Q7dspOvakVyggidGImIMp3x9t7e6QhvcsK1edMyeP5u2WxvgakifXAn3is7XgsRM/8iHnYthI3CWsuLV66N0ipBk3aiSO7QgZb9mSuitN0R1QQX9/+D0+C5RsjWhvW9G+fA4PBM74Zfcf4oPduDFkh4aGuhpDWlVl1sZRWVszRQD1laDUEtXFvRO8lSLMb1EcMRulQif9M0NH3YVUuIoKW1freX7yxco3N5kh0RZ+S9VSfhVdvH5Nk4SzF4YH+ZxBpc+BsaJTiQ0vd93uw78OQuRpVYcSgZ7ZZeB0iq6BaGqQyCju2t4iJnkIeCOOWWf/Fi6l8sy46mbaPRjjMVIvzvDOqsqfN+4/vWVWaUWtaEVUwvU3VaJYe692U+rL369VZ5NQhAqfpLhg1QIwmjiBbln2hQOc2X98BIm2xCEEp81/4JZ8y9GMM4YgO30VncX4c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
